### ISSUE TITLE
自建数据集

### ISSUE THREAD

**Issue by yuanyangwangTJ** [MedlarTea/MPF_GRR_SLT#1]
看到你们的论文中提到了自建数据集，请问这个数据集会公开吗？

**Comment by MedlarTea** [comment]
可以参考我们"Robot Person Following Under Partial Occlusion"文章中的数据集，于此处可以下载：https://drive.google.com/drive/folders/1M-H4Y2WA5zNn9-LnSy6RL25OTnucDGzc?usp=drive_link

**Comment by yuanyangwangTJ** [comment]
> 可以参考我们"Robot Person Following Under Partial Occlusion"文章中的数据集，于此处可以下载：https://drive.google.com/drive/folders/1M-H4Y2WA5zNn9-LnSy6RL25OTnucDGzc?usp=drive_link

非常感谢！
